# Travis yml file inspired by scikit-bio
# Check on http://lint.travis-ci.org/ after modifying it!
sudo: false
language: python
env:
  - PYVERSION=3.5 USE_CYTHON=TRUE
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - conda create --yes -n test_env python=$PYVERSION --file ci/conda_requirements.txt -c biocore
  - conda install --yes -n test_env cython pytest pytest-cov
  - source activate test_env
  - pip install https://github.com/qiime2/qiime2/archive/master.zip https://github.com/qiime2/q2-types/archive/master.zip
  - pip install flake8 coveralls
  - pip install .
  - git clone https://github.com/qiime2/q2lint
script:
  - py.test --cov=q2_composition
  - flake8
  - python q2lint/q2lint.py
after_success:
  - coveralls
notifications:
  webhooks:
    on_success: change
    on_failure: always
