{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-composition
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-bio
    - biom-format >=2.1.5,<2.2.0
    - scipy
    - pandas >=0.23.0
    - qiime2 {{ release }}.*
    - q2templates {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_composition
    - qiime2.plugins.composition

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
